### ISSUE TITLE
Weird coloring and `@apply` issues in SCSS files (or in Vue SFCs)

### ISSUE THREAD

**Issue by eggsy** [windicss/windicss-intellisense#114]
[Here's my repo](https://github.com/eggsy/website), you can see that I have `src/stylesheets/scrollbar.scss` that is imported within a `root.scss` file in the same directory, and I import that root in my `nuxt.config.js` > `css`. When I tried using Windi classes (with `@apply`), it didn't work in those files (you can check blame to see how I switched to variables instead). This only happens for external SCSS files. I tried some methods, putting that directory in `includes` of `windi.config.js` but no luck there either.

There's also another issue with `@apply` in both external files and in SFC style tags. They're not colored, which makes it look like it's not a part of the code. I don't think it's because of my VSC theme (I use Dracula) because, before the switch from Tailwind's official extension, they were all colored with no problems.

![image](https://user-images.githubusercontent.com/13917975/117311510-e96fba00-ae8c-11eb-9b97-bc29d7d770f9.png)

You see that the coloring of `@apply` is missing and all classes look weird. You can [see here how it was when using Tailwind's extension](https://user-images.githubusercontent.com/13917975/117311696-1a4fef00-ae8d-11eb-9da8-8f15c3023cf2.png)).

🌟 **One idea!**

One thing I always cried about Tailwind's extension is that it wasn't able to sort classes in `@apply`. It's not important but it'd be amazing to see this in Windi's extension! If this is possible, I can create a different issue for this!

**Comment by alexanderniebuhr** [comment]
can you try to add following in your VS Code Editor Settings
```
  "windicss.includeLanguages": {
    "scss": "css",
  },
  ```

**Comment by eggsy** [comment]
> 
> 
> can you try to add following in your VS Code Editor Settings
> 
> ```
>   "windicss.includeLanguages": {
>     "scss": "css",
>   },
> ```

Nope, didn't work.

**Comment by eggsy** [comment]
Yep, it looks fine in SFCs `<style>` tags and it's now working in my `.scss` files too. I can use classes but seems like colours are still missing from there. Is it supposed to be like this?

![image](https://user-images.githubusercontent.com/13917975/118838118-192bb280-b8ce-11eb-8670-ce7e78c66e8b.png)

**Comment by alexanderniebuhr** [comment]
@eggsy if you talk about issue in functionality of actual usage it might be wrong repo to have this issue. If you are talking about bug in VS Code Extension it is correct. Not sure what you mean?

**Comment by alexanderniebuhr** [comment]
ok, so maybe please open for the second part an additional issue. It confused me sorry

**Comment by alexanderniebuhr** [comment]
@eggsy you checked the includeLanguages setting?
example:
```
"windicss.includeLanguages": {
  "ruest": "html", // css, js
  "svelte": {
    "type": "css"
  },
  "javascriptreact": {
    "type": "js",
    "patterns": ["@apply\s+\S+$", "..." ],
  },
}
```

**Comment by eggsy** [comment]
@alexanderniebuhr didn't fix it. I don't know if that's the right config though, it says `javascriptreact` all I'm trying to achieve is get `@apply`s coloured in `.scss` files.

**Comment by alexanderniebuhr** [comment]
It's just an example config, cause that setting supports more stuff

**Comment by voorjaar** [comment]
v0.16.6 should fix all problems, try it please.

**Comment by eggsy** [comment]
Welp, they work as expected now! Even in commented lines, they are highlighted (might be a bug of my theme or I don't know but sure!). It'd be great if that's fixed in the next patch though 😅.

![image](https://user-images.githubusercontent.com/13917975/118864177-63ba2880-b8e8-11eb-8086-9da30bd074cb.png)

**Comment by alexanderniebuhr** [comment]
just going to close since there was no much activity lately, if some issue still exists please reopen a new issue
